Repository openshift/aws-vpce-operator, pull requests merged in 2025-05, with the labels that each got.

#299 Bump boilerplate and add Aurora as reviewers
  .github/dependabot.yml
  OWNERS
  OWNERS_ALIASES
  boilerplate/_data/last-boilerplate-commit
  boilerplate/openshift/golang-osd-operator-osde2e/README.md
  boilerplate/openshift/golang-osd-operator-osde2e/standard.mk
  boilerplate/openshift/golang-osd-operator-osde2e/test-harness-template.yml
  boilerplate/openshift/golang-osd-operator-osde2e/update
  boilerplate/openshift/golang-osd-operator/OWNERS_ALIASES
  boilerplate/openshift/golang-osd-operator/ensure.sh
  boilerplate/openshift/golang-osd-operator/standard.mk
  boilerplate/openshift/golang-osd-operator/update
  build/Dockerfile
  build/Dockerfile.olm-registry
  test/e2e/README.md
  test/e2e/test-harness-template.yml
Labels: tide/merge-method-squash, lgtm, approved

#298 SREP-148: Ensure aws-vpce-operator is logging at verbosity 0
  controllers/vpcendpoint/validation.go
Labels: lgtm, approved, jira/valid-reference

#300 Update OWNERS
  OWNERS
Labels: lgtm, approved
